ada-url/ada-python

.github/workflows/build_test.yml, .github/workflows/lint.yml, docs/conf.py, docs/index.rst, setup.cfg
This PR:
* Changes references to `ada-url/python` to `ada-url/ada-python`
* Splits the GitHub Actions workflows. Building and testing are now separate from linting.
* Updates the compatibility level for Linux wheels. The ones produced by the GHA runners should be able to run on a wider variety of systems.
=> Update repo links, split GHA workflows, make Linux wheels more compatible

ada_url/ada_adapter.py, tests/test_ada_url.py
This PR exposes the `URL` attributes to the `dir()` function in Python.
=> Add directory listing to URL class

README.rst
In my view, the README is currently too minimalist. Most people do not know much about URL standards. By default, many people rely on urllib, but it is important to explain why that might be a problem if you care about the WHATWG standard.
=> Documenting what the library does.

README.rst, ada_url/ada_adapter.py, tests/test_ada_url.py
Re: [this discussion](https://github.com/ada-url/ada-python/pull/1#issuecomment-1553531106), this PR re-works how the objects from the C library are managed.
Previously I was using `__enter__` and `__exit__` to ensure that `ada_free` got called. But CFFI provides [`ffi.gc`](https://cffi.readthedocs.io/en/latest/ref.html#ffi-gc-1), which can do this automatically:
>ffi.gc(cdata, destructor, size=0): return a new cdata object that points to the same data. Later, when this new cdata object is garbage-collected, destructor(old_cdata_object) will be called
This allows us to avoid the overhead of `__enter__` and `__exit__`. On a benchmark script this saved roughly 20% of execution time.
=> Use ffi.gc to handle object lifecycle

ada_url/ada.cpp, ada_url/ada.h
This PR synchronizes the C library with the newly-released 2.4.2 version of `ada`.
=> Upgrade ada C library to 2.4.2

ada_url/ada_adapter.py, tests/test_ada_url.py
This PR adds `__str__` and `__repr__` methods to the `URL` class, such that objects now return a friendly representation based on their `href`.
=> Add __str__ and __repr__ methods

.github/workflows/build.yml, .github/workflows/unit-tests.yml, Makefile, pyproject.toml
This PR updates the build configuration for GitHub Actions, such that more compatible wheels are produced.
I was previously using `auditwheel` manually for Linux builds; this function is now performed by `cibuildwheel`.
macOS builds are also more compatible, using `delocate`.
These are the ones I'll post to PyPI.
=> Build wheels with cibuildwheel

ada_url/ada.cpp, ada_url/ada.h, setup.cfg
This PR updates `ada` to 2.5.0, and the version for this library to 0.2.0 (should we call it 1.0.0?).
=> Upgrade to ada 2.5.0

ada_url/ada_adapter.py
This PR fixes a mistake in the docstring for `ada_url.URL.can_parse`. The `base` and `url` arguments were reversed.
=> Update example for URL.can_parse

setup.cfg
This PR updates the version number for the package. I'll release this to PyPI, so users can get the ada 2.5.1 changes.
=> Bump version to 1.0.1 for ada 2.5.1

.github/workflows/build.yml
Re: Issue #15, this PR updates the `build.yml` file such that:
* The action runs when a new GitHub release is created
* A source distribution (`.tar.gz`) is created
* The source distribution and binary distributions (`.whl`) are uploaded to PyPI
I am drawing from these docs:
* [`cibuildwheel/examples/github-deploy.yml`](https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml)
* [Publishing with a Trusted Publisher](https://docs.pypi.org/trusted-publishers/using-a-publisher/)
I have created a GitHub "environment" called `release` for publishing. I will [configure PyPI](https://github.com/ada-url/ada-python/assets/1922815/53676601-9afe-4ee7-8e78-23cde147a1bb) to use it as well.
=> Publish to PyPI on release

.github/workflows/build.yml
Like https://github.com/ada-url/ada-python/pull/17, but for later in the file. The linter now thinks the YAML file is valid...
=> Fix another build.yml syntax error

.github/workflows/build.yml
This PR updates `build.yml` to fix [this issue](https://github.com/ada-url/ada-python/actions/runs/5189343000/jobs/9354691643) that affects the automated release.
=> Fix artifact name for package release

ada_url/__init__.py, ada_url/ada.cpp, ada_url/ada.h, ada_url/ada_adapter.py, ada_url/ada_c.h, docs/index.rst, tests/test_ada_url.py
This PR:
* Upgrades to the latest version of `ada_url`
* Adds the `host_type` to the `URL` class and to the `parse_url` function output
* Adds support for the `del` operator, using the `ada_clear_*` functions
The Host Type is returned as an `IntEnum`, whose values can be compared to normal integers.
=> Version 1.2.0: ada_url to 2.6.5, host_type support

ada_url/ada_adapter.py, setup.cfg
=> feat: type annotations

ada_url/__init__.py, ada_url/ada.cpp, ada_url/ada.h, ada_url/ada_adapter.py, ada_url/ada_c.h, docs/index.rst, tests/test_ada_url.py
This PR adds support for the `ada_get_schema_type` added in [ada 2.6.6](https://github.com/ada-url/ada/pull/503). Per the discussion in that PR, I'll update this for the rename to `get_scheme_type` and adjust the code here to remove the adapter.
Update: now this PR uses 2.6.7.
=> Add scheme_type for ada 2.6.7

Makefile, pyproject.toml
If we install ada_url on macOS M1 then we will get this error:
```
$ pip3 install ada_url==1.3.0
...
$ python3 -c "import ada_url"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File ".../python/3.11.3/lib/python3.11/site-packages/ada_url/__init__.py", line 1, in <module>
from ada_url.ada_adapter import (
File ".../installs/python/3.11.3/lib/python3.11/site-packages/ada_url/ada_adapter.py", line 4, in <module>
from ada_url._ada_wrapper import ffi, lib
ImportError: dlopen(.../installs/python/3.11.3/lib/python3.11/site-packages/ada_url/_ada_wrapper.abi3.so, 0x0002): symbol not found in flat namespace '_ada_can_parse'
```
GitHub Actions doesn’t support macOS arm64 (M1/Apple Silicon) managed runners, so we need to do cross-compilation on macOS. `cibuildwheel` sets …
=> Fix macOS arm64 and universal2 wheels

README.rst
Fix the name of the package from `boto3-helpers` to `ada_url` in the installation instructions.
=> docs: fix install command

README.rst, ada_url/ada.cpp, ada_url/ada.h, docs/index.rst, setup.cfg
This PR upgrades `ada` to the latest and greatest, prepares for the next PyPI release, and adds more examples to the documentation.
Resolves #42
=> Release 1.7.0, includes Ada 2.7.2

.github/workflows/build.yml, pyproject.toml
Also aim to fix #24.
Thanks @plusiv for https://github.com/ada-url/ada-python/pull/46#issuecomment-1776388272, where he came up with the solution.
It's a little bit tricky: maybe `make` cannot work with `vcvars64.bat` to modify the env, so I use a long `before-build`.
And I don't know how to choose from `vcvars64.bat` and `vcvars32.bat` by the OS arch. So only x64 wheels are available.
----
Some questions:
* Why do we include `.o`, `.cpp`, `.c`, `.h` files in the wheels? Afaik, ada works well without them.
* `pip install ada_url --no-binary ada_url` will fail (on both Linux and Windows) because of the absence of `ada.o`, same as https://github.com/ada-url/ada-python/pull/46#issuecomment-1776388272. Maybe we can open a new issue for this?
----
[Microsoft Visual C++ 2015-2022 …
=> ci: add Windows x64 wheels

README.rst, ada_url/ada_adapter.py
This change aims to use the built-in function `len()` for getting the search params passed to the class `URLSearchParams`, instead of using the `size` property, `len` is a more pythonic and idiomatic way to retrieve a count of items.
```python
>>> from ada_url import URLSearchParams
>>> obj = URLSearchParams('key1=value1&key2=value2&key2=value3')
>>> len(obj)
3
```
=> Feat: Add  `len` builtin function to `URLSearchParams` class 

benchmark.py
This PR adds a benchmark script for comparing to `urllib.parse.urllparse`.
The WPT test URLs are available in already in the test suite, so I used them for comparison.
Resolves #59
=> Add benchmark script

README.rst
Should be self-explanatory. This is just documentation.
=> [skip ci] documenting can_ada and standard compliance

requirements/development.txt
This PR is aimed at fixing the issue described [here](https://github.com/ada-url/ada-python/pull/72#issuecomment-2059515911). Hopefully Dependabot will get the idea.
=> Use version specifiers for Sphinx requirements

.github/workflows/build.yml, Makefile, requirements/base.txt, requirements/development.txt
Similar to PR #76, this one pins additional dependencies with different versions for 3.8 and 3.9+.
Python 3.8 goes EOL in October, so this will probably stop happening then.
=> More Sphinx pins for Dependabot

ada_url/ada_adapter.py
The default value for `encode` and `decode` is utf-8. We don't need to explicitly define it.
=> fix: use default value for encode and decode

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml, MANIFEST.in, Makefile, ada_url/ada_build.py, docs/index.rst, pyproject.toml, requirements/base.txt, requirements/development.txt, setup.py
=> Fix ada.o object build

pyproject.toml
Probably a good idea to build wheels for the latest pypy release.
=> Add pypy 3.10 wheel build

.github/workflows/build.yml
It appears this is causing some wheels to not get uploaded to pypi.
=> Remove overwrite from upload-artifact

.github/workflows/lint.yml, .github/workflows/unit-tests.yml, pyproject.toml
Python 3.8 went end of life on the 7th. This PR drops testing for that version, which was preventing some upgrades of development dependencies (particularly Sphinx for docs).
=> Drop 3.8-specific items

ada_url/ada.cpp, ada_url/ada.h, pyproject.toml
This PR updates to `ada` 3.1.1.
=> Updates for ada 3.1.1 / version 1.18.0

ada_url/ada.cpp, ada_url/ada.h, pyproject.toml
This PR upgrades to ada 3.1.2.
=> Updates for ada 3.1.2 / version 1.19.0

ada_url/ada.cpp, ada_url/ada.h
=> Updates for ada 3.1.3 / version 1.20.0

ada_url/ada_adapter.py
This PR fixes the type hint for `idna.encode`. Closes #106.
=> Update type hint for idna.encode

ada_url/ada.cpp, ada_url/ada.h, ada_url/ada_build.py, pyproject.toml
This PR upgrades to `ada` 3.2.4.
=> Changes for version 1.23.0 / ada 3.2.4
